name: Build WF
on:
  push:
    branches:
      - main
  
  pull_request:
    brances: ["main"]

  workflow_dispatch:
  
  schedule:
    - cron: "0 20 * * 1-5" # monday to friday every night 8pm this will trigger mm HH DD MM DOW

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Maven Build
        run: mvn install
  
  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Run Tests on main branches
        run : mvn test
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle